# Generated by Django 5.2.8 on 2025-11-24 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_solicitudprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='prestamos.socio'),
        ),
    ]
